In [1]:
import numpy as np
import math as mt
import random 

In [83]:
a=np.array([1,2,3])
b=np.array([1,2,3])
a

print(a, b)

[1 2 3] [1 2 3]


# ARRAY

In [15]:
a=[]

for i in range(1,8):
     int_1=int(input("enter your value"))
        a.append(int_1)
        
print(np.array(a))

IndentationError: unexpected indent (2828308924.py, line 5)

In [16]:
arr = np.array((1, 2, 3, 4, 5))

print(arr)


[1 2 3 4 5]


In [20]:

# arr = np.array([[1 , 2 , 3]],[[4 , 5 , 6]])
arr = np.array([[1, 2, 3], [4, 5, 6]]) # 2d
#arr=np.array([[[1 , 2 , 3] , [4 , 5 , 6] , [7 , 8 , 9]]]) #3d
print(arr)

[[1 2 3]
 [4 5 6]]


In [28]:
arr.ndim #check dimanshan
arr.size

4

In [31]:
arr.shape #(roq ,column)

(4,)

In [33]:
arr.dtype

dtype('float64')

# Slice_Numpy-

In [35]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr[0:2])

[[1 2 3]
 [4 5 6]]


# Data Types in Python

In [36]:
# strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
# integer - used to represent integer numbers. e.g. -1, -2, -3
# float - used to represent real numbers. e.g. 1.2, 42.42
# boolean - used to represent True or False.
# complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

SyntaxError: invalid syntax (613162345.py, line 1)

In [44]:
m=np.array(["jugal" , "kankia" , "karan" , "anku"])
print(m)
print(m.dtype)

['jugal' 'kankia' 'karan' 'anku']
<U6


In [45]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


# NumPy Array Copy vs View

In [46]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [49]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x.base)

[42  2  3  4  5]
[42  2  3  4  5]


# NumPy Array Reshaping

In [53]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [54]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [55]:

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


# NumPy Joining Array


In [59]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
#newarr = np.add(arr1, arr2)
print(arr)

[1 2 3 4 5 6]


In [65]:

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [60]:

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [63]:

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


# Splitting NumPy Arrays

In [70]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 2)

print(newarr)
print(newarr[0])
print(newarr[1])


[array([1, 2, 3]), array([4, 5, 6])]
[1 2 3]
[4 5 6]


In [71]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


# Searching Arrays

In [72]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [74]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [75]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [76]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


In [77]:

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


# Random smapling with NumpY

In [84]:
np.random.random (1)

array([0.41865825])

In [86]:
np.random.random ((3,3))

array([[0.00589924, 0.19451268, 0.5844503 ],
       [0.43795726, 0.06367635, 0.88328082],
       [0.07673915, 0.83620087, 0.81184042]])

In [89]:
np.random.randint(1,4,5)

array([1, 1, 1, 3, 3])

In [97]:
np.random.randint(1,10,(3,4,4))

array([[[9, 3, 1, 7],
        [8, 9, 2, 8],
        [2, 5, 1, 9],
        [6, 5, 8, 9]],

       [[9, 3, 7, 3],
        [9, 9, 7, 7],
        [6, 7, 1, 1],
        [7, 2, 9, 2]],

       [[3, 9, 6, 1],
        [3, 8, 4, 1],
        [5, 3, 1, 4],
        [4, 2, 3, 6]]])

In [95]:
np.random.seed(10)#same value all time 
np.random.randint(2,10,(3,4,4))
#2**32-1 random functione

array([[[3, 7, 6, 9],
        [2, 3, 5, 6],
        [3, 7, 2, 7],
        [3, 4, 2, 3]],

       [[2, 4, 2, 8],
        [6, 5, 2, 6],
        [9, 5, 8, 2],
        [5, 4, 8, 3]],

       [[2, 6, 8, 3],
        [5, 8, 7, 7],
        [7, 5, 3, 8],
        [7, 6, 8, 8]]])

In [96]:
np.random.rand(3,3)

array([[0.44183317, 0.43401399, 0.61776698],
       [0.51313824, 0.65039718, 0.60103895],
       [0.8052232 , 0.52164715, 0.90864888]])

In [99]:
x=[1,2,3,4]

np.random.choice(x)

3